name: Deploy My App

on:
  push:
    branches:
      - main # Trigger setiap push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PrivateKey }}

      - name: Set environment variables from secrets
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      - name: Deploy and Build on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.141.194.211 << 'EOF'
            # pastikan directorynya ada
            sudo mkdir -p /var/www/mywebsite/runningCICD
            cd /var/www/mywebsite/runningCICD

            # pull source terbaru
            git pull origin main

            # install dependency nodejs
            npm install

            # build project
            npm run build

            # copy hasil build ke direktori nginx
            sudo rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/

            # restart nginx supaya file baru dibaca
            sudo systemctl restart nginx
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PrivateKey }}
